services:
  mongodb:
    image: mongo:7.0.4
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    command: [--auth]
    volumes:
      - CoMission_Platform-MongoVolume:/data/db
    networks:
      - test_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Seoul
      - LC_ALL=C.UTF-8
    volumes:
      - CoMission_Platform-MysqlVolume:/var/lib/mysql
    networks:
      - test_network

  spring-boot-app:
    image: dongick/comission-platform
    container_name: comission-platform
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mongodb
      - mysql
      - influxdb
    volumes:
      - /home/ubuntu/backend/logs:/logs
      - C:\Users\lg\Documents\GITHUB\progress-tracker\backend\src\main\resources\static\missions:/missions
      - C:\Users\lg\Documents\GITHUB\progress-tracker\backend\src\main\resources\static\authentications:/authentications
    networks:
      - test_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3005:3000'
    networks:
      - test_network
    depends_on:
      - influxdb
    volumes:
      - grafana-volume:/var/lib/grafana
    user : root

  influxdb:
    image: influxdb:1.8.5
    container_name: influxdb
    restart: always
    ports:
      - '8086:8086'
    networks:
      - test_network
    volumes:
      - influxdb-volume:/var/lib/influxdb

networks:
  test_network:

volumes:
  CoMission_Platform-MongoVolume:
    external: true
  CoMission_Platform-MysqlVolume:
    external: true
  influxdb-volume:
    external: true
  grafana-volume:
    external: true