export const AUTHENTICATION_ERROR = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DUPLICATE_AUTHENTICATION: "DUPLICATE_AUTHENTICATION",
  MISSION_NOT_STARTED: "MISSION_NOT_STARTED",
  MISSION_ALREADY_COMPLETED: "MISSION_ALREADY_COMPLETED",
  EXCEEDED_AUTHENTICATION_LIMIT: "EXCEEDED_AUTHENTICATION_LIMIT",
};

export const GLOBAL_ERROR = {
  ACCESS_TOKEN_INVALID: "액세스 토큰이 유효하지 않습니다",
  ACCESS_TOKEN_EXPIRED: "액세스 토큰이 만료되었습니다",
  REFRESH_TOKEN_INVALID: "리프레시 토큰이 유효하지 않습니다",
  REFRESH_TOKEN_EXPIRED: "리프레시 토큰이 만료되었습니다",
  UNAUTHORIZED: "토큰이 존재하지 않습니다",
};
